# Generated by Django 3.2.9 on 2024-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_auto_20240220_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadd',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
