# Generated by Django 3.2.9 on 2024-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_alter_imageadd_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadd',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
